export const backendUrlteacherRegister = "http://localhost:4000/online_course/TeacherApi/registerTeacher/";
export const backendUrlteacherLogin="http://localhost:4000/online_course/TeacherApi/authenticate_teacher/";
export const backendUrlstudentLogin="http://localhost:4000/online_course/StudentApi/authenticate_student/";
export const backendUrlstudentRegister = "http://localhost:4000/online_course/StudentApi/registerStudent/";
export const backendUploadImage = "http://localhost:4000/online_course/CouseApi/UploadImage/";
export const backendUrlCourseAdd = "http://localhost:4000/online_course/CouseApi/addCourse/";
export const backendUrlgetAllCourses = "http://localhost:4000/online_course/CouseApi/getAllCourses/";
export const backendUrlgetCoursesBySearch = "http://localhost:4000/online_course/CouseApi/getAllCourses/";
export const backendUrlEnrollCourse = "http://localhost:4000/online_course/EnrollApi/enroll/";